### PR TITLE
Update bootloader from FW on STM32F7

### PR DESCRIPTION
**Pull request by DanielePettenuzzo**
The pixhawk 4 bootloader to flash firmware on telem2 was added to the ROMFS and now by setting the SYS_BL_UPDATE parameter to 1 and rebooting will automatically update the bootloader. 

@bresch FYI

### CODE REVIEW

**Comment by DanielePettenuzzo** [comment]
This has been tested today

**Comment by DanielePettenuzzo** [comment]
@julianoes the commits from David are already in a pr upstream. I would like to get the bootloader change for the pixhawk 4 into the Bootloader upstream since it makes more sense to flash firmware on TELEM2 (usually companion link). Then I could add the binary to the firmware just in case someone wants to update to this

**Comment by DanielePettenuzzo** [comment]
https://github.com/PX4/Firmware/pull/11394

**Comment by julianoes** [comment]
Don't forget to delete branches after merging, thx.

**Comment by davids5** [comment]
@DanielePettenuzzo @julianoes - I am looking for a vote of confidence. A bad bootloader upgrade will brick HW.  How much testing has been done on this? Units and updates? Were there any issues at all? Did all updates result in the upgrade?

**Pull request merged**
